### ISSUE TITLE
AMM / Bank Panel

### ISSUE THREAD

**Issue by RedBeardEth** [BibliothecaForAdventurers/realms-react#191]
- [x] add tx sidebar meta messages
- [x] loading state while trade occurring
- [x] dynamically load rates (every 20 seconds and before purchasing?)
- [ ] notification / selection of slippage?
- [x] LP functionality (add remove liquidity)

**Comment by ponderingdemocritus** [comment]
I'm going to tackle the LP functionality

**Comment by ponderingdemocritus** [comment]
Mostly complete - leaving dynamically loading rates to when @tenoxious updates the indexer, this is also needed to illustrate slippage

**Comment by tenoxious** [comment]
> Mostly complete - leaving dynamically loading rates to when @tenoxious updates the indexer, this is also needed to illustrate slippage

Indexer should be updated now
